### PR TITLE
Expect component in integration tests

### LINKED ISSUE #22: expectComponent does not work with hbs rendering
`expectElement` works:

```javascript
test('it renders', function (assert) {
  assert.expect(1);

  this.render(hbs`
    {{#my-component class="my-component"}}
      Some text here
    {{/my-component}}
  `);

  expectElement(".my-component", 1);
});
```

We would prefer to use `expectComponent` to write this as

```javascript
test('it renders', function (assert) {
  assert.expect(1);

  this.render(hbs`
    {{#my-component}}
      Some text here
    {{/my-component}}
  `);

  expectComponent("my-component", 1);
});
```

but this fails in `Component.detectInstance`.

### PR DESCRIPTION
**Pull request by bantic**
Fixes #22, #23

### CODE REVIEW

File: Brocfile.js [hunk 1]
```diff
@@ -1,20 +1,16 @@
...
 
 var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
 
-var app = new EmberAddon();
+/*
+  This Brocfile specifes the options for the dummy test app of this
+  addon, located in `/tests/dummy`
+
+  This Brocfile does *not* influence how the addon or the app using it
+  behave. You most likely want to be modifying `./index.js` or app's Brocfile
```
Comment (mixonic) [inline Brocfile.js]: `using it behaves`?

`or the app's Brocfile`

also I think the file is now `ember-cli-build.js`?

Comment (bantic) [inline Brocfile.js]: Ah, this was the default text from the ember-cli upgrade. According to the notes this is needed for the dummy app that runs the acceptance test. I'll try removing it and if there's no error I'll leave it out

Comment (bantic) [inline Brocfile.js]: yep, works fine without it. dropped in a153d476ee3fcf79b706df43b2911b9a060f1c01
